language: ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

env:
  - TRAVIS=1